-- SM 모듈(시스템운영관리) 산하 화면들을 화면 단위 프로젝트/DLL(WYNLAB.SM.MENU/USER/USERAUTH/
-- USERGROUP)에서 모듈 단위 프로젝트/DLL(WYNLAB.SM 하나)로 병합했다. 클래스 이름/네임스페이스는
-- 그대로이고(서브모듈 폴더로만 구분, WYNLAB.SM.csproj 헤더 주석 참고) 어셈블리 이름만
-- "WYNLAB.SM"으로 바뀐다.

UPDATE TSMMENU SET FORM_CLASS_NM = 'WYNLAB.SM.MENU.MenuListForm, WYNLAB.SM' WHERE MENU_CD = 'SM_MENU';
UPDATE TSMMENU SET FORM_CLASS_NM = 'WYNLAB.SM.USER.frmUserManage, WYNLAB.SM' WHERE MENU_CD = 'SM_USER';
UPDATE TSMMENU SET FORM_CLASS_NM = 'WYNLAB.SM.USERGROUP.UserGroupListForm, WYNLAB.SM' WHERE MENU_CD = 'SM_USERGRP';
UPDATE TSMMENU SET FORM_CLASS_NM = 'WYNLAB.SM.USERAUTH.PermissionAssignForm, WYNLAB.SM' WHERE MENU_CD = 'SM_AUTH';
GO

SELECT MENU_CD, MENU_NM, FORM_CLASS_NM FROM TSMMENU WHERE MENU_CD IN ('SM_MENU','SM_USER','SM_USERGRP','SM_AUTH') ORDER BY MENU_CD;
GO
