-- TSMMENU에 BA_ORG_DEPT(부서등록)/BA_ORG_EMP(사원등록)/BA_CUST_REG(거래처등록)는 이미 메뉴
-- 트리 자리만 잡혀 있었고(FORM_CLASS_NM이 NULL이라 메뉴를 눌러도 "화면을 찾을 수 없습니다"),
-- 방금 WYNLAB.BA 모듈에 그 세 화면을 만들었으니 여기서 연결한다.

UPDATE TSMMENU SET FORM_CLASS_NM = 'WYNLAB.BA.frmDept, WYNLAB.BA' WHERE MENU_CD = 'BA_ORG_DEPT';
UPDATE TSMMENU SET FORM_CLASS_NM = 'WYNLAB.BA.frmEmp, WYNLAB.BA' WHERE MENU_CD = 'BA_ORG_EMP';
UPDATE TSMMENU SET FORM_CLASS_NM = 'WYNLAB.BA.frmCust, WYNLAB.BA' WHERE MENU_CD = 'BA_CUST_REG';
GO

SELECT MENU_CD, MENU_NM, FORM_CLASS_NM FROM TSMMENU WHERE MENU_CD IN ('BA_ORG_DEPT', 'BA_ORG_EMP', 'BA_CUST_REG');
GO
