-- frmItemGroup -> frmItemGrp 클래스명 변경 반영.
UPDATE TSMMENU SET FORM_CLASS_NM = 'WYNLAB.BA.frmItemGrp, WYNLAB.BA' WHERE MENU_CD = 'BA_ITEMGRP';
GO

SELECT MENU_CD, MENU_NM, FORM_CLASS_NM FROM TSMMENU WHERE MENU_CD = 'BA_ITEMGRP';
GO
