-- TBAITEM 키를 item_cd -> ITEM_ID(자동증가)로 바꾼다. item_cd는 이제 그냥 업무상 품목코드일
-- 뿐 DB 키가 아니다. SQL Server는 기존 컬럼에 IDENTITY 속성을 얹을 수 없어서(ALTER COLUMN
-- 불가), 테이블이 아직 비어있는 지금(0건, 직접 확인함) 컬럼을 지웠다가 IDENTITY로 다시
-- 만드는 방식으로 처리한다 - 데이터가 있는 상태였다면 이 방식은 못 쓴다.

ALTER TABLE TBAITEM DROP CONSTRAINT [PK__TBAITEM__52025D1597A5667F];
ALTER TABLE TBAITEM DROP COLUMN ITEM_ID;
ALTER TABLE TBAITEM ADD ITEM_ID BIGINT IDENTITY(1, 1) NOT NULL;
ALTER TABLE TBAITEM ADD CONSTRAINT PK_TBAITEM PRIMARY KEY (ITEM_ID);
GO

SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TBAITEM' AND COLUMN_NAME IN ('ITEM_ID', 'item_cd');
SELECT tc.CONSTRAINT_NAME, c.COLUMN_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE c ON tc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
WHERE tc.TABLE_NAME = 'TBAITEM' AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY';
GO
