-- 범용 데이터 통로(api/data/*)는 메뉴마다 TSMMENU.PROC_PREFIX가 등록돼 있어야 그 접두사로
-- 시작하는 프로시저만 호출을 허용한다(DataController.ValidateAsync ②, 004 마이그레이션 참고).
-- BA 화면 5개 전부 이 값이 비어있어서 "이 메뉴는 범용 데이터 통로를 사용하도록 설정되어
-- 있지 않습니다" 403으로 막히고 있었다 - SM_MINOR_CODE(USP_SM_MINORCODE_)와 같은 규칙으로 채운다.

UPDATE TSMMENU SET PROC_PREFIX = 'USP_BA_DEPT_' WHERE MENU_CD = 'BA_DEPT';
UPDATE TSMMENU SET PROC_PREFIX = 'USP_BA_EMP_' WHERE MENU_CD = 'BA_EMP';
UPDATE TSMMENU SET PROC_PREFIX = 'USP_BA_CUST_' WHERE MENU_CD = 'BA_CUST';
UPDATE TSMMENU SET PROC_PREFIX = 'USP_BA_ITEM_' WHERE MENU_CD = 'BA_ITEM';
UPDATE TSMMENU SET PROC_PREFIX = 'USP_BA_ITEMGRP_' WHERE MENU_CD = 'BA_ITEMGRP';
GO

SELECT MENU_CD, PROC_PREFIX FROM TSMMENU WHERE MENU_CD IN ('BA_DEPT', 'BA_EMP', 'BA_CUST', 'BA_ITEM', 'BA_ITEMGRP') ORDER BY MENU_CD;
GO
