-- SM 모듈 그룹코드(SM_USRG/SM_MENUG/SM_CODEG)를 새 관례(BA_ITEM_G처럼 언더스코어로 구분)에
-- 맞춰 SM_USR_G/SM_MENU_G/SM_CODE_G로 정정한다. 자식 메뉴의 UPPER_MENU_CD와, 이미 이 그룹
-- 코드로 권한이 부여된 TSMMENUAUTH 행(있으면)도 같이 옮겨야 기존 권한 설정이 안 끊긴다.

UPDATE TSMMENU SET UPPER_MENU_CD = 'SM_USR_G'  WHERE UPPER_MENU_CD = 'SM_USRG';
UPDATE TSMMENU SET UPPER_MENU_CD = 'SM_MENU_G' WHERE UPPER_MENU_CD = 'SM_MENUG';
UPDATE TSMMENU SET UPPER_MENU_CD = 'SM_CODE_G' WHERE UPPER_MENU_CD = 'SM_CODEG';

UPDATE TSMMENU SET MENU_CD = 'SM_USR_G'  WHERE MENU_CD = 'SM_USRG';
UPDATE TSMMENU SET MENU_CD = 'SM_MENU_G' WHERE MENU_CD = 'SM_MENUG';
UPDATE TSMMENU SET MENU_CD = 'SM_CODE_G' WHERE MENU_CD = 'SM_CODEG';

UPDATE TSMMENUAUTH SET MENU_CD = 'SM_USR_G'  WHERE MENU_CD = 'SM_USRG';
UPDATE TSMMENUAUTH SET MENU_CD = 'SM_MENU_G' WHERE MENU_CD = 'SM_MENUG';
UPDATE TSMMENUAUTH SET MENU_CD = 'SM_CODE_G' WHERE MENU_CD = 'SM_CODEG';
GO
