-- 구매요청등록(frmPoReq) 메뉴 등록 - 자재관리(10) > 구매요청관리(13) 밑에 붙인다(2026-09-22).
IF NOT EXISTS (SELECT 1 FROM TSMMENU WHERE MODULE = 'MA' AND SCREEN_CLASS_NM = 'frmPoReq')
BEGIN
    INSERT INTO TSMMENU (MENU_NM, UPPER_MENU_ID, MENU_LEVEL, MENU_TYPE, MODULE, SCREEN_CLASS_NM, PROC_PREFIX, SORT_ORDER, USE_YN, reg_user_id, reg_dt)
    VALUES (N'구매요청등록', 13, 3, 'FORM', 'MA', 'frmPoReq', 'USP_MA_', 10, 'Y', SUSER_SNAME(), GETDATE());
END
GO
