-- 구매발주등록(frmPoOrder) 메뉴 등록 - 자재관리(10) > 구매발주관리(12) 밑.
IF NOT EXISTS (SELECT 1 FROM TSMMENU WHERE MODULE = 'MA' AND SCREEN_CLASS_NM = 'frmPoOrder')
BEGIN
    INSERT INTO TSMMENU (MENU_NM, UPPER_MENU_ID, MENU_LEVEL, MENU_TYPE, MODULE, SCREEN_CLASS_NM, PROC_PREFIX, SORT_ORDER, USE_YN, reg_user_id, reg_dt)
    VALUES (N'구매발주등록', 12, 3, 'FORM', 'MA', 'frmPoOrder', 'USP_MA_', 10, 'Y', SUSER_SNAME(), GETDATE());
END
GO
