-- 기초재고등록 / 기타출고요청등록 / 기타출고등록 메뉴 (2026-10-03, WYNLAB_DEV 전용)
-- 재고관리 그룹(MENU_ID 79: 재고현황 10, 수불현황 20) 아래에 3개 화면을 추가하고, 메뉴 권한은 구매입고등록(frmGr)과 같은 대상에게 똑같이 준다.
-- 여러 번 실행해도 안전하다(SCREEN_CLASS_NM으로 존재 확인).

DECLARE @grp BIGINT = (SELECT MENU_ID FROM TSMMENU WHERE MENU_NM = N'재고관리' AND MENU_TYPE = 'GROUP' AND UPPER_MENU_ID = 10);
DECLARE @tpl BIGINT = (SELECT MENU_ID FROM TSMMENU WHERE SCREEN_CLASS_NM = 'frmGr');

DECLARE @items TABLE (cls VARCHAR(100), nm NVARCHAR(100), so INT);
INSERT INTO @items VALUES ('frmOpenStock', N'기초재고등록', 30), ('frmEtcOutReq', N'기타출고요청등록', 40), ('frmEtcOut', N'기타출고등록', 50);

INSERT INTO TSMMENU (MENU_NM, UPPER_MENU_ID, MENU_LEVEL, MENU_TYPE, MODULE, SCREEN_CLASS_NM, PROC_PREFIX, SORT_ORDER, USE_YN, reg_user_id, reg_dt)
SELECT i.nm, @grp, 3, 'FORM', 'MA', i.cls, 'USP_MA_', i.so, 'Y', 'wynlab', GETDATE()
FROM @items i
WHERE @grp IS NOT NULL AND NOT EXISTS (SELECT 1 FROM TSMMENU m WHERE m.SCREEN_CLASS_NM = i.cls);

INSERT INTO TSMMENUAUTH (MENU_ID, AUTH_TARGET_TYPE, AUTH_TARGET_CD, VIEW_YN, INSERT_YN, DELETE_YN, SAVE_YN, PRINT_YN, EXCEL_YN,
                         AUTH01, AUTH02, AUTH03, AUTH04, AUTH05, AUTH06, AUTH07, AUTH08, AUTH09, AUTH10, REG_USER_ID, REG_DT)
SELECT m.MENU_ID, a.AUTH_TARGET_TYPE, a.AUTH_TARGET_CD, a.VIEW_YN, a.INSERT_YN, a.DELETE_YN, a.SAVE_YN, a.PRINT_YN, a.EXCEL_YN,
       a.AUTH01, a.AUTH02, a.AUTH03, a.AUTH04, a.AUTH05, a.AUTH06, a.AUTH07, a.AUTH08, a.AUTH09, a.AUTH10, 'wynlab', GETDATE()
FROM TSMMENU m
JOIN @items i ON i.cls = m.SCREEN_CLASS_NM
JOIN TSMMENUAUTH a ON a.MENU_ID = @tpl
WHERE NOT EXISTS (SELECT 1 FROM TSMMENUAUTH x WHERE x.MENU_ID = m.MENU_ID AND x.AUTH_TARGET_TYPE = a.AUTH_TARGET_TYPE AND x.AUTH_TARGET_CD = a.AUTH_TARGET_CD);
GO
